Update setup.py
Update to make it compatible with the latest pip release (>=20.1.1) which generates an error while installing vip_hci:

The command python setup.py develop
returned the following error:

Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    reqs = [str(ir.req) for ir in reqs]
  File "setup.py", line 40, in <listcomp>
    reqs = [str(ir.req) for ir in reqs]
AttributeError: 'ParsedRequirement' object has no attribute 'req'

The 'ParsedRequirement' object has now an attribute called requirement. The proposed change is retro-compatible.